title:            QC's blog
description:      Something about OpenWrt and other cool things
duoshuo_shortname: yichya-blog
reading_time:     false
words_per_minute: 2000
logo:             images/logo.png
# Your site's domain goes here (eg: //mmistakes.github.io, http://mademistakes.com, etc)
# When testing locally leave blank or use http://localhost:4000
url: https://blog.yichyaqc.cn

menu:
  - title: 'Home'
    url: '/'
#  - title: 'Categories'
#    url: '/categories'
#    type: 'categories'
  - title: 'About'
    url: '/about'
#  - title: 'Tags'
#    url: '/tags'
#  - title: 'Favorites'
#    url: '#'
#    submenu:
#      - title: 'highlighter'
#        url: '/code-highlighting-post/'
#      - title: 'intro'
#        url: '/readability-post/'

# Owner/author information
owner:
  name:           yichya QC
  site:           https://blog.yichyaqc.cn
  avatar:         images/avatar.jpg
  bio:            "A good soldier knows there's only one thing he can rely on when the chips are down: Not his cutting-edge intel, not his state of the art equipment, and not his top of the line weapon. Just himself: It took me a long time to remember that. <br/> --- Laurence \"Prophet\" Barnes"
  email:          yichya@outlook.com
  # Social networking links used in footer. Update and remove as you like.
  ## twitter: 
  ## facebook: 
  ## github: 
  ## stackexchange:
  ## linkedin:
  ## instagram:
  ## flickr:
  ## tumblr:
  # google plus id, include the '+', eg +AronBordin
  ## google_plus:    

## social:
##  - title: "github"
##    url: "https://github.com/aron-bordin"
##  - title: "linkedin"
##    url: "https://br.linkedin.com/in/aronbordin"
##  - title: "youtube"
##    url: "https://www.youtube.com/channel/UCfnSek-9HPWOx5e2pH7VFgg"
# Background image to be tiled on all pages
## background:

# Analytics and webmaster tools stuff goes here
## google_analytics:
## google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
## bing_verify:

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Asia/Shanghai
future:      true
highlighter: pygments
markdown:    kramdown
gems:
  - jekyll-sitemap
  - jekyll-paginate
sass:
  sass_dir: _sass
  style: compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

# Amount of post to show on home page
paginate: 5

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  syntax_highlighter: pygments

syntax_highlighter_opts:
  line_numbers: true
  line_numbers_start: 1
  tab_width: 4
  bold_every: 10
  css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
